version: '3.3'
services:
  api:
    container_name: libreweather_api
    image: ghcr.io/libreweather/libre-weather-api:latest
    env_file: .env
    restart: unless-stopped
    network_mode: host
    ports:
      - '3000:3000'
